### PR TITLE
cannot open a directory with file get contents

### PR DESCRIPTION
**Pull request by gabidj**
* [x] I am the author of this code or the code is public domain
* [x] I release this code into the public domain

### CODE REVIEW

**Comment by emilengler** [comment]
What are you trying to achieve with this?

**Comment by ryangurn** [comment]
I do not know that this will help anything. The error you where most likely getting was related to `$config['feed_dir'] ` not existing. Which can be solved with what you did, however, that will remove any hope of this being dynamic and changeable using the configuration. Please see PR #236 and look at the same section of code and you can see a different way of doing this.

**Comment by emilengler** [comment]
Closing this, author has no longer motivation on the PR

**Comment by gabidj** [comment]
Feed dir is a directory. as per code. 
`$xml = file_get_contents($config['absoluteurl'] . $config['feed_dir']);`
 suggests opening a directory as a file
`$xml = file_get_contents($config['absoluteurl'] . $config['feed_dir']) . '/feed.xml';`
Opens the xml. I wouldn't add the xml part in the `feed_dir` because feed dir might be used in other places as a directory.

Sorry for the late response. I must have lost the track with this pr.

**Comment by gabidj** [comment]
This was a fix for an initial install error. 

Alternatively you may rename `feed_dir` to `feed_path`.

What does `feed_dir` is it the feed dir or the xml path.

**Comment by emilengler** [comment]
Oh right looks like I was bit stupid there, will merge

**Comment by emilengler** [comment]
Thanks! Merged with some adjustments

**Pull request closed without merging**
