### PR TITLE
feat(themes/default): add HTML <link> tag for podcast feed

### PR DESCRIPTION
**Pull request by coldacid**
Add a link element in the page `<head>` that references the podcast RSS feed via feed.php.

* [x] I am the author of this code or the code is public domain
* [x] I release this code under the [GPL-3.0 License](https://github.com/PodcastGenerator/PodcastGenerator/blob/master/LICENSE)

### CODE REVIEW

**Comment by coldacid** [comment]
I wrote this to use feed.php but out of box nothing actually seems to use that script. The default RSS button goes to feed.xml for example. Perhaps the link tag should as well? @emilengler

**Comment by emilengler** [comment]
> I wrote this to use feed.php but out of box nothing actually seems to use that script. The default RSS button goes to feed.xml for example. Perhaps the link tag should as well? @emilengler

What's wrong with just referring to feed.xml?

**Comment by coldacid** [comment]
Nothing wrong with it, I just used feed.php for some reason (probably because I fixed the problem with it elsewhere) and wondered if using it was the right way to go. I'll change it over to use the XML file instead.

**Comment by emilengler** [comment]
Ok thanks, will merge! First I need to apologize for my inactivity. I will review your high-quality patches now :-)

**Pull request closed without merging**
