### PR TITLE
New Dark Theme

### PR DESCRIPTION
**Pull request by NeaMitika**
Made the Black version of the Default Theme
preview

### CODE REVIEW

**Comment by emilengler** [comment]
Thanks! I will review soon

**Comment by linkmauve** [comment]
Hi, instead of making a full new theme, maybe have a look at the [prefers-color-scheme: dark](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-color-scheme) media query, it lets the user state their preference and get the expected theme in return, without having to select it manually on each website, or worse let the website owner have to pick the right theme.

**Comment by NeaMitika** [comment]
@linkmauve  i am not that good of a "developer" do make this kind of implementations, but i am growing fast lately i will be on that level one day!

This is a free and open source project, you are wormly invited to make the implementations your self and share it so it can be included inside the project.

**Comment by linkmauve** [comment]
Hey @NeaMitika!

I’ve made a proposal in #363, which makes the default theme adapt itself to the user’s preference. :)

**Comment by NeaMitika** [comment]
> Hey @NeaMitika!
> 
> I’ve made a proposal in #363, which makes the default theme adapt itself to the user’s preference. :)

You're on fire!!!!

**Comment by emilengler** [comment]
Thanks for all your kind PRs! I will have some free time starting on the weekend and I will spent some time on PG then again :-)

**Pull request closed without merging**
