### PR TITLE
Docs update00

### PR DESCRIPTION
**Pull request by suorcd**
* [x] I am the author of this code or the code is public domain
* [x] I release this code into the public domain

The file looked like it was trying to be a MD, so it was renamed
With the new file extension, a MD linter was ran on the file and it was updated.
The commands were wrapped in bash code blocks

On Ubuntu 22.04
I noticed that apache2 was being installed that was due to installing the PHP package; so that was removed
Since there is no DB the related PHP packages were also removed

The steps were broken out into a couple sections and re-numbered

The version was set to a variable at beginning

For the NGINX conf there was a mis-order of step. The user was being told to 'cleanup' the files, which deleted the desired file.
So it was not found in the subsequent steps.
The NGINX conf needed to be updated for the newer version of Ubuntu LTS.

For certbot, since we are on Ubuntu, using the snapd version should provide a more up-to-date package that'll work longer.

### CODE REVIEW

**Comment by coldacid** [comment]
INSTALL and INSTALL.nginx (which is a copy of the former but edited for nginx) are plain text files, but I suppose a conversion to Markdown isn't a bad idea. Could you make the same formatting changes to INSTALL and rename it as well, so that these files remain consistent?

Also, Codacy is raising a [bunch of complaints](https://app.codacy.com/gh/PodcastGenerator/PodcastGenerator/pullRequest?prid=9513769) about the formatting of INSTALL.nginx.md. Primarily, lines outside of code blocks should be no more than 80 characters, and bare URLs should be wrapped in angle brackets. Could you fix that up as well? Thanks.

**Comment by suorcd** [comment]
I've updated the INSTALL.md file. I'm not sure if prefork or mpm_event should have been used, since bother were kinda being setup; so i went with mpm_event. There were a few extra steps needed. Someone else should test the steps.

Working on Codacy.

**Comment by suorcd** [comment]
I'm not sure what you want to do with this last complaint.

**Comment by coldacid** [comment]
Yeah that last one is dumb and shouldn't be showing as an issue in Codacy.

**Pull request merged**
