### PR TITLE
Fixing #304

### LINKED ISSUE #304: quotation sign defaces after edit of an entry.
**System Information**
Podcast Generator Version: 3.1
Webserver: Apache
PHP Version:7.3

When this:

image

Is edited in Admin mode and I am simply hitting "Save" without changing anything, it defaces to this:

image

### PR DESCRIPTION
**Pull request by ryangurn**
This PR is to fix #304 and allow for quotes in the title of a podcast, we will still check for all other types of code in the string however this will allow for single and double quotes only. 
 
@emilengler this should be pretty simple to merge I hope.

* [x] I am the author of this code or the code is public domain
* [x] I release this code into the public domain

### CODE REVIEW

**Review by emilengler — APPROVED** [review]
Thanks

**Comment by emilengler** [comment]
By the way, if you want to work on something you could also work on implementing an API for PG

**Comment by ryangurn** [comment]
@emilengler what type of API are we looking for, that might be something useful to do when we have figured out a way to support SQL in some form!

**Comment by emilengler** [comment]
The API I was looking for was some kind of administration API. This would allow people to create scripts, apps and much more. Having an API for users would make no sense. We already have the RSS feed which is easily readable :P

**Pull request closed without merging**
