### PR TITLE
Fixing #296 & #297

### LINKED ISSUE #296: Auto-Indexing new episodes broken in 3.0.1 and 3.1
found out that the Auto index feature broken in 3.0: I tried uploading an episode via ftp and normally I would click "auto index" and it would automatically find it and generate the fitting xml file along with it. However it said "found!" in green letters. then went at "edit episode" page but there was no new entry there.
 
Then I delted the /media/index.html and 2020-06-27 file as they appear to have 0 bytes.
Now the function auto index does not even run anymore and is stuck endlessly.
 
If I copy back the index.htm from a backup it unstuck the auto-indexing feauture but still the newly added mp3 is not found.

In 3.1 it is even worse, it will simply say "no new files found".

As the file is too big for github, I sent the MP3 to you via WeTransfer now.

### LINKED ISSUE #297: manually uploading MP3 files not possible in 3.0.1. and 3.1
As auto-indexing stopped working for me (see #296), I tried with manually adding the episode via upload within the admin panel  as the file size is below 105 MB  but I do get then
 
ERROR 500 - Internal Server Error!
The following error occurred:
The requested URL caused an internal server error.
 
If you get this message repeatedly please contact the webmaster.

As the file is too big for github, I sent the MP3 to you via WeTransfer now.

### PR DESCRIPTION
**Pull request by ryangurn**
Adding additional characters to the `$strictfilenamepolicy` config to allow for dashes and other European characters. This should help fix #296 & fix #297

* [x] I am the author of this code or the code is public domain
* [x] I release this code into the public domain

### CODE REVIEW

**Comment by ryangurn** [comment]
Sorry that this includes the changes already made for 304, but it should merge with zero artifacts.

**Comment by emilengler** [comment]
Sorry I disagree with that change, please don't take this as any kind of punishment.
If we include that change, what would be the point of having the `$strictfilenamepolicy` option then? Would it even have a notable effect when disabled?
Since 35236058ca86512f272fd9f125d359358b6a2a11 new installations automatically have strictfilenamepolicy set to "no" because it caused so much trouble in the past

**Comment by emilengler** [comment]
I probably think it's better to discuss a complete remove of that option. It's a thing from the past

**Comment by ryangurn** [comment]
If we want to remove this option, I could handle that. In the past, what was the reason for needing this type of strict file name configuration?

**Comment by emilengler** [comment]
> In the past, what was the reason for needing this type of strict file name configuration?

I'm the wrong person to ask here, I took over in 2019. I personally believe it's because many web browsers or web servers were not able to handle international filenames. This should be fixed now and if people still have problems with it is there responsibility to use non complex ones. Feel free to remove the feature :-)

**Comment by ryangurn** [comment]
I will send a PR for that in the next couple of minutes since I do believe that all modern web browsers support international standards for language.

**Comment by ryangurn** [comment]
@emilengler, I removed the configuration and I'm running more substantial tests now. I am running into some interesting things that will need to be fixed so please wait before merging the PR.

**Comment by ryangurn** [comment]
I believe that I have fixed any UTF-8 encoding issues with uploading files with names that include non UTF-8 characters.

**Comment by ryangurn** [comment]
@emilengler please test this really well since it seems that accents, umlauts and ligatures.

**Comment by emilengler** [comment]
This does not work, function `mb_convert_encoding` is not found. I think adding the php-mbstirng library isn't a good solution.

**Comment by ryangurn** [comment]
@emilengler okay, thats a 🤦. I think that us requiring a strict naming convention is a good idea since there are lots of issues when we start including accents and such. I think that I will close this PR and say that we should keep the setup the way that it is currently. 

We should provide more documentation and explicitly say that we need the file name to fall under [a-zA-Z0-9]. There are too many edge cases in which this could fail and cause users errors.

**Pull request closed without merging**
