### PR TITLE
HTML improvements for the login.php

### PR DESCRIPTION
**Pull request by NeaMitika**
* [x ] I am the author of this code or the code is public domain
* [x ] I release this code into the public domain

Improvements to the HTML so it can be more User-Friendly

### CODE REVIEW

**Comment by emilengler** [comment]
Thanks!
Looks awesome now

**Comment by NeaMitika** [comment]
I am glad you liked it!
I am working on some improvements for the default theme too.
As you can see in them image below.
image
But i still have some question about some parts of code, for example i see there is code that it doesnt work for me, for example : 

`// Check for image
        // The imgPG value has the highest priority
        if ($item[$i]["episode"]["imgPG"] != "") {
            echo '  <br>';
        } elseif (
            file_exists($config["absoluteurl"] . $config["img_dir"] . $item[$i]["episode"]["fileid"] . '.jpg') ||
            file_exists($config["absoluteurl"] . $config["img_dir"] . $item[$i]["episode"]["fileid"] . '.png')
        ) {`
It doesnt show the image, but maby its only a bad setting on my end.

**Comment by emilengler** [comment]
Hello @NeaMitika!
I really enjoy you like Podcast Generator and do some theme design!
I can understand your problem with the code. I wanted to make a new theme system for 3.2 as the current one is not really good and is more like a system rather than a theme, that's why you don't understand the code. To tell you what the code does, it displays an episode cover if the user uploaded/set one. I also like the logo you are working on. But it has too much text on it, to me it looks more like an advertisement banner.

By the way, I just released 3.1

**Comment by NeaMitika** [comment]
Oh wow nice 3.1, gonna check it out ASAP. 

I will improve the logo! Thx for the tip!

**Pull request closed without merging**
