### PR TITLE
Added Support for adding Episode Covers

### PR DESCRIPTION
**Pull request by NicolaiVdS**
* [x] I am the author of this code or the code is public domain
* [x] I release this code into the public domain

### CODE REVIEW

**Comment by NicolaiVdS** [comment]
Do not accept yet forgot to add it to the edit episode section

**Comment by NicolaiVdS** [comment]
Did this really quick might need some cleanup

**Comment by coldacid** [comment]
How does this interact with pulling the episode cover from the cover art image in the MP3 itself?

**Comment by coldacid** [comment]
@NicolaiVdS have you tested how this works in the following scenarios?

* Episode mp3 has an embedded episode cover, user uploads a separate cover image on the add podcast episode page
* Episode mp3 has an embedded episode cover, user does not upload a separate cover image on the add podcast episode page
* Episode mp3 has an embedded episode cover, user attaches a new cover image on the edit podcast episode page

**Comment by coldacid** [comment]
#481 subsumes this PR

**Pull request closed without merging**
