### PR TITLE
Updated the preview.png

### PR DESCRIPTION
**Pull request by NeaMitika**
New preview.png for the light theme, i have added 3 podcasts with some random cover arts just to fill in the coverart spot.

* [x] I am the author of this code or the code is public domain
* [x] I release this code into the public domain

preview

### CODE REVIEW

**Comment by kalvinmattheus** [comment]
Looks great! Please note if PR #290 is approved there will be a search bar under the jumbotron.

**Comment by NeaMitika** [comment]
> Looks great! Please note if PR #290 is approved there will be a search bar under the jumbotron.

i have made it a Draft, i will update it when the Search Bar PR will be merged... btw i like the search bar a lot , great job!

**Comment by emilengler** [comment]
That was exactly what I was looking for. By the way, we don't need to wait for #290. Merging this won't collide with the other PR.

**Comment by NeaMitika** [comment]
> That was exactly what I was looking for. By the way, we don't need to wait for #290. Merging this won't collide with the other PR.

yes, but it will not have the search bar inside the preview.png
Dont worry as soon as you will merge the #290 i will remake the preview.png with the search bar, it's fine

**Comment by emilengler** [comment]
Oh right forgot that^^

**Comment by emilengler** [comment]
@NeaMitika Please update, the pull request from @kalvinmattheus was merged today

**Comment by NeaMitika** [comment]
I dont know what this is
 `Merge branch 'master' of https://github.com/NeaMitika/PodcastGenerator`

**Comment by NeaMitika** [comment]
If this PR doesnt work or its made wrong... cancel it i will redo it....

**Comment by emilengler** [comment]
Thanks

**Pull request closed without merging**
